# #################################### #
# Configuration file for Hakoirimusume #
# #################################### #
# ${VAR_NAME} will be replaced with the value of the environment variable VAR_NAME.
# See docs/configuration.md for more information.

# For testing
os.environ.path: ${PATH}

# Flask server
server.port: 8080

# LINE Messaging API
line.bot:
  channel-token: ${LINE_CHANNEL_ACCESS_TOKEN}
  channel-secret: ${LINE_CHANNEL_SECRET}
  handler.path: /callback

# Imgur API 
imgur:
  client-id: ${IMGUR_CLIENT_ID}

# PiCamera & Sensor
hardware:
  camera-image: true  # If false, image area of Rabbit's House Report will be disappeared.
  bme280.i2c-bus: 1
  bme280.i2c-address: 0x76

# Hakoirimusume application
hakoirimusume:
  alert:
    condition:  # [!This value can be changed via LINE!]
      temperature: 26.5  # °C  float
      humidity: 60  # %  float
      pressure: null  # hPa  float
    interval: 3  # hour
    restrict:
      times-of-day: 5
      disable-message-threshold: 180  # messages / month
    action:
      type: null  # GET | POST | COMMAND | null
      # The following placeholders are available in 'target', 'header', 'body'.
      # {{IMAGE_URL}} : Imgur URL of image (will be replaced with empty string when camera image is not available)
      # {{TEMP}} : Current temperature (e.g., 25.0)
      # {{HUMID}} : Current humidity (e.g., 50.0)
      # {{PRESSURE}} : Current pressure (e.g., 1013.0)
      # {{DATE}} : yyyymmdd string of current date (e.g., 20240425)
      # {{TIME}} : HHMMSS string of current local time (e.g., 113911)
      target: null  # URL (type is GET or POST) | shell command (type is COMMAND) | null
      header: null  # String | null, ignored if type is not POST
      body: null  # String | null, ignored if type is not POST
      success-message: "冷房を点けたよ！"  # String | null
      failure-message: "冷房を点けるのに失敗しちゃった、部屋に来て点けて！"  # String | null
  # Aikotoba configs
  aikotoba:
    timeout: 60  # sec.
    sheeds: 
      - ["お利口で", "かしこくて", "賢くて", "かわいくて", "可愛くて", "キュートで", "げんきで", "元気で", "人見知りで", "優しくて"]
      - ["ご機嫌な", "自立した", "よく食べる", "食欲旺盛な", "天才な", "なんでも食べる？", "長寿な", "長生きな", "甘えん坊な", "癒される"]
      - ["うさぎ", "ウサギ", "Rabbit", "ラビット", "うさちゃん", "うさぎちゃん", "箱入り娘", "耳の長い家族", "ドワーフ", "お姫さま"]
  info.show-ip: true  # If true, show private IP address on the info command
  request.timeout: 300  # sec.
  remote-shutdown:
    enable: true
    available-authority-level: user  # user | admin
    exec: "sudo shutdown -h now"

# Generative filepaths
filepaths:
  database: "./hakoirimusume.db"
  sensor-data: "./sensor-data.csv"
  log: "./hakoirimusume.log"