# LINE BOT Hakoirimusume Configuration File
#
# For configuration items not listed in this file, default values are used.
# Default values are defined in model/config_loader.py file.

[General]
port = 21212
data_dir = "data"
database_Name = "database.db"

[Hakoirimusume]
initial_aikotoba = "はこいりむすめ"
