# #################################### #
# Configuration file for Hakoirimusume #
# #################################### #
# ${VAR_NAME} will be replaced with the value of the environment variable VAR_NAME.
# See docs/configuration.md for more information.

# For testing
os.environ.path: ${PATH}

# Server
server.port: 80


# Imgur API 
imgur.client-id: ${IMGUR_CLIENT_ID}

# PiCamera & Sensor
hardware:
  pi-camera: yes  # If false, image area of Rabbit's House Report will be disappeared.
  bme280.i2c-bus: 1
  bme280.i2c-address: 0x77

# Generative filepaths
filepath.sensor-data: "./sensor-data.csv"